#!/usr/bin/env node

// GULP-GITHOOKS START
var exec = require('child_process').exec;

exec('gulp lint -s >temp/git_commit.txt', {
    cwd: 'd:\\projects\\spumante'
}, function (err, stdout, stderr) {
    console.info(stdout);
    var exitCode = 0;
    if (err) {
        console.error(stderr);
        exitCode = -1;
    }
    process.exit(exitCode);
});

// GULP-GITHOOKS END